apiVersion: v1
kind: Service
metadata:
  name: ipl-service
spec:
  selector:
    app: ipl
  ports:
    - protocol: TCP
      port: 3000  #svc port number to access app on web browser
      targetPort: 3000   # container port number
  type: LoadBalancer